name: Daily Data Update

on:
  schedule:
    - cron: '0 8 * * *'   # 12:00 UAE (UTC+4)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm i

      - name: Run scraper
        run: npm run scrape

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "chore(data): update snapshots [skip ci]" || echo "No changes"
          git push